apiVersion: v1
kind: Service
metadata:
  labels:
    app: notes    
  name: notes
  namespace: demo
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 6111
  selector:
    app: notes    
  type: ClusterIP
